
GET http://localhost:3000/users/me/2

####
GET http://localhost:3000/users



####
POST http://localhost:3000/users/
Content-Type: application/json

{
    "first_name": "Suborno",
    "last_name": "Das",
    "username": "subornodas",
    "email": "Goat@gmail.com",
    "password": "asoif",
    "age": 40
}
#######
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "Goat@gmail.com",
    "password": "asoif"
}

####
PUT http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkdvYXRAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IlN1Ym9ybm8iLCJsYXN0X25hbWUiOiJEYXMiLCJ1c2VybmFtZSI6InN1Ym9ybm9kYXMiLCJhZ2UiOjQwLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NzEyMTU3M30.2mU4VrMriRiuVIsJfhnlP87BwpvlT3K75b_OyEsJYMg

{
    "email": "goat@gmail.com",
    "age": 23
}


####
DELETE http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkdvYXRAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IlN1Ym9ybm8iLCJsYXN0X25hbWUiOiJEYXMiLCJ1c2VybmFtZSI6InN1Ym9ybm9kYXMiLCJhZ2UiOjQwLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NzEyMTU3M30.2mU4VrMriRiuVIsJfhnlP87BwpvlT3K75b_OyEsJYMg

