GET http://localhost:3000/admin

###
POST http://localhost:3000/admin
Content-Type: application/json

{
    "first_name": "Sukanta",
    "last_name": "Majumdar",
    "role":"admin",
    "username": "sukanta@456",
    "email": "Goat60@gmail.com",
    "password": "asoif",
    "age": 40
}

###
POST http://localhost:3000/admin/login
Content-Type: application/json

{
    "username": "sukanta@456",
    "password": "asoif"
}
###

PUT http://localhost:3000/admin/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkdvYXRAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IlN1Ym9ybm8iLCJsYXN0X25hbWUiOiJEYXMiLCJ1c2VybmFtZSI6InN1Ym9ybm9kYXMiLCJhZ2UiOjIzLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTYwMzU1MX0.VrH1qFoGX72d-z9eGrAkdrUL3CJH39U0_B-ZFyFtL_U

{
    "username": "sukanta@456"
}

####

DELETE http://localhost:3000/admin/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkdvYXRAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IlN1Ym9ybm8iLCJsYXN0X25hbWUiOiJEYXMiLCJ1c2VybmFtZSI6InN1Ym9ybm9kYXMiLCJhZ2UiOjIzLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTYwMzU1MX0.VrH1qFoGX72d-z9eGrAkdrUL3CJH39U0_B-ZFyFtL_U


