
GET http://localhost:3000/users/me/3

####
GET http://localhost:3000/users



####
POST http://localhost:3000/users/
Content-Type: application/json

{
    "first_name": "Suborno",
    "last_name": "Das",
    "username": "subornodas",
    "email": "Goat@gmail.com",
    "password": "asoif",
    "age": 40
}
#######
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "Goat@gmail.com",
    "password": "asoif"
}

####
PUT http://localhost:3000/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkdvYXRAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IlN1Ym9ybm8iLCJsYXN0X25hbWUiOiJEYXMiLCJ1c2VybmFtZSI6InN1Ym9ybm9kYXMiLCJhZ2UiOjQwLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTUyNjMyNH0.-VasWZqg3aFVs5bWi44qB6wCgtC9KrXzoPA8Ql2r7OQ

{
    "email": "Goat@gmail.com",
    "age": 23
}


####
DELETE http://localhost:3000/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkdvYXRAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IlN1Ym9ybm8iLCJsYXN0X25hbWUiOiJEYXMiLCJ1c2VybmFtZSI6InN1Ym9ybm9kYXMiLCJhZ2UiOjQwLCJyb2xlIjoidXNlciIsImlhdCI6MTY5OTUyNTk5MH0.jxP2wQEQGtHDQbaZTW9BClqlpsp5QEnFvuI0V_YbWdA

